/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}"
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Design tokens from DESIGN.md
        surface: '#fff8f7',
        'surface-dim': '#ecd5d3',
        'surface-bright': '#fff8f7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fff0ef',
        'surface-container': '#ffe9e7',
        'surface-container-high': '#fae3e1',
        'surface-container-highest': '#f5dddb',
        'on-surface': '#251918',
        'on-surface-variant': '#584140',
        'inverse-surface': '#3b2d2c',
        'inverse-on-surface': '#ffedeb',
        outline: '#8c716f',
        'outline-variant': '#dfbfbd',
        'surface-tint': '#ab3334',
        primary: '#942225',
        'on-primary': '#ffffff',
        'primary-container': '#b53a3a',
        'on-primary-container': '#ffdcd9',
        'inverse-primary': '#ffb3ae',
        secondary: '#904c2e',
        'on-secondary': '#ffffff',
        'secondary-container': '#fea682',
        'on-secondary-container': '#78391d',
        tertiary: '#6c4525',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#875c3b',
        'on-tertiary-container': '#ffdec7',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdad7',
        'primary-fixed-dim': '#ffb3ae',
        'on-primary-fixed': '#410005',
        'on-primary-fixed-variant': '#8a1a1f',
        'secondary-fixed': '#ffdbce',
        'secondary-fixed-dim': '#ffb598',
        'on-secondary-fixed': '#370e00',
        'on-secondary-fixed-variant': '#733519',
        'tertiary-fixed': '#ffdcc4',
        'tertiary-fixed-dim': '#f2bb93',
        'on-tertiary-fixed': '#2f1500',
        'on-tertiary-fixed-variant': '#643e1f',
        background: '#fff8f7',
        'on-background': '#251918',
        'surface-variant': '#f5dddb',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '80px',
        'gutter': '32px',
        'stack-sm': '12px',
        'stack-md': '20px',
        'stack-lg': '40px',
        'stack-xl': '80px',
        'margin-mobile': '24px',
        'container-max': '1440px',
      },
      fontFamily: {
        'display-lg': ['Playfair Display', 'serif'],
        'display-lg-mobile': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'headline-sm': ['Playfair Display', 'serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'ui-label': ['Inter', 'sans-serif'],
        'ui-small': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'ui-label': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'ui-small': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      boxShadow: {
        'soft': '0 4px 20px rgba(47, 47, 47, 0.05)',
        'soft-hover': '0 12px 30px rgba(47, 47, 47, 0.08)',
        'card': '0 4px 20px rgba(47, 47, 47, 0.05)',
        'card-hover': '0 12px 30px rgba(47, 47, 47, 0.08)',
        'elevated': '0 20px 40px rgba(47, 47, 47, 0.1)',
      },
      transitionTimingFunction: {
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'spring': 'cubic-bezier(0.23, 1, 0.32, 1)',
      },
      transitionDuration: {
        'fast': '150ms',
        'normal': '200ms',
        'slow': '300ms',
        'slower': '500ms',
        'slowest': '800ms',
      },
      animation: {
        'fade-in': 'fadeIn 0.8s cubic-bezier(0.4, 0, 0.2, 1) forwards',
        'slide-up': 'slideUp 0.8s cubic-bezier(0.4, 0, 0.2, 1) forwards',
        'slide-down': 'slideDown 0.8s cubic-bezier(0.4, 0, 0.2, 1) forwards',
        'scale-in': 'scaleIn 0.6s cubic-bezier(0.23, 1, 0.32, 1) forwards',
        'mask-reveal': 'maskReveal 1.2s cubic-bezier(0.77, 0, 0.175, 1) forwards',
        'blur-reveal': 'blurReveal 1s cubic-bezier(0.23, 1, 0.32, 1) forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        maskReveal: {
          '0%': { clipPath: 'inset(0 0 100% 0)' },
          '100%': { clipPath: 'inset(0 0 0 0)' },
        },
        blurReveal: {
          '0%': { filter: 'blur(20px)', opacity: '0', transform: 'translateY(30px)' },
          '100%': { filter: 'blur(0)', opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}